### PR TITLE
Restore compatibility with latest nightly (and make this fork up to date in general)

### PR DESCRIPTION
**Pull request by motin**
This [applies](https://github.com/browsermt/bergamot-browser-extension/commit/236f72ee051fae7e996354f0a05271499af1bdc9) the changeset from https://phabricator.services.mozilla.com/D107755#change-ejYef3i1CbQL that was intended to update the infobar invocation to the changed notification interface in tree, as well as [fixes the typo in that changeset](https://github.com/browsermt/bergamot-browser-extension/commit/ca7bbd0c866f9161affe9f87a8a5c0006346ff9d), so that the Firefox Translations UI works again with the current Nightly.

Screenshot:
Screenshot 2021-10-29 at 09 23

Note: Since https://github.com/mozilla-extensions/firefox-translations is currently archived, and the new repo at https://github.com/mozilla/firefox-translations is [empty without any commits, progress or information](https://github.com/mozilla/firefox-translations/issues/1), I am making the PR here instead. As a result, this PR also includes all the changes from https://github.com/mozilla-extensions/firefox-translations since this fork was created as well.

### CODE REVIEW

**Comment by kpu** [comment]
Oh hi @motin, how do I use this given that the usage instructions refer to the broken version?

**Comment by jerinphilip** [comment]
@kpu Downloading the generated xpi and installing it (simply opening it and clicking ahead) to my previously configured nightly worked for me on Windows.

https://github.com/jerinphilip/bergamot-browser-extension/actions/runs/1400979181

Note: GitHub actions double zips the xpi, so please unzip to find the actual xpi within.

image
image

**Comment by jerinphilip** [comment]
https://github.com/mozilla-extensions/firefox-translations/issues/89

Just remembered this thread which is the only configuration I ever did to get it working, because I built in and Mozilla didn't and wasn't signed.

**Comment by andrenatal** [comment]
Just a heads-up that although apparently functional, the code in display here is not going to continue to be officially maintained  by Mozilla due to performance and stability issues, and lack of documentation and compatibility with Firefox's system add-ons architecture.

It can of course be used for demo purposes but it won't make to the integrated version in gecko-dev.

**Pull request merged**
